version: '2.1'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=super_user
      - POSTGRES_PASSWORD=super_user_password
    ports:
      - '5432:5432'
    volumes:
      - ./init-data/:/docker-entrypoint-initdb.d/
    env_file: ./.env

  app:
    depends_on:
      - postgres
    build: .
    ports:
      - 8080:8080
    env_file: ./.env
    volumes:
      - .m2:/root/.m2
