#!/bin/bash
set -e

psql -e --username "super_user" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $MY_POSTGRES_USER WITH PASSWORD '$MY_POSTGRES_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $MY_POSTGRES_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $MY_POSTGRES_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $MY_POSTGRES_USER;
EOSQL